import { createHash } from 'node:crypto'; import type { Pool } from 'pg';
export interface RpaEvent { schema_version:1; event_id:string; run_id:string; bot_id:string; project_id:string; environment:'dev'|'uat'|'prod'|'local'|'unknown'; event_type:'started'|'completed'|'failed'|'cancelled'|'skipped'; occurred_at:string; metrics?:Record<string,number>; error?:{code?:string;summary?:string}; evidence?:Record<string,unknown>; }
export interface WorkflowEvent { schema_version:1; event_id:string; aggregate_type:'ai_sdlc_job'|'project_plan'|'deployment'; aggregate_id:string; event_type:string; occurred_at:string; payload:Record<string,unknown>; }
export class ReportingError extends Error{constructor(message:string,readonly status=400,readonly code='INVALID_REQUEST'){super(message);}}
export class ReportingService{
 constructor(private readonly pool:Pool,private readonly alertTarget:string){}
 async ingest(event:RpaEvent){validate(event);const inserted=await this.pool.query('INSERT INTO rpa_run_events(event_id,run_id,bot_id,project_id,environment,event_type,occurred_at,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb) ON CONFLICT(event_id) DO NOTHING RETURNING event_id',[event.event_id,event.run_id,event.bot_id,event.project_id,event.environment,event.event_type,event.occurred_at,JSON.stringify(sanitize(event))]);if(inserted.rowCount&&event.event_type==='failed'&&event.environment==='prod'){const window=new Date(event.occurred_at).toISOString().slice(0,13);const id=`alert:${hash(`${event.bot_id}:${event.environment}:${event.error?.code??'UNKNOWN'}:${window}`)}`;const message=`RPA critical failure\nBot: ${event.bot_id}\nEnvironment: prod\nCode: ${safe(event.error?.code??'UNKNOWN')}\nCorrelation: ${event.event_id}`;await this.enqueue(id,this.alertTarget,message);}return{accepted:true,duplicate:inserted.rowCount===0,event_id:event.event_id};}
 async ingestWorkflow(event:WorkflowEvent){validateWorkflow(event);const clean=sanitize(event);const inserted=await this.pool.query('INSERT INTO workflow_events(event_id,aggregate_type,aggregate_id,event_type,occurred_at,payload) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT(event_id) DO NOTHING RETURNING event_id',[event.event_id,event.aggregate_type,event.aggregate_id,event.event_type,event.occurred_at,JSON.stringify(clean.payload)]);if(inserted.rowCount){const evidence=typeof clean.payload.evidence_ref==='string'?`\nEvidence: ${safe(clean.payload.evidence_ref)}`:'';await this.enqueue(`workflow:${event.event_id}`,this.alertTarget,`${label(event.aggregate_type)} ${safe(event.event_type)}\nID: ${safe(event.aggregate_id)}${evidence}`);}return{accepted:true,duplicate:inserted.rowCount===0,event_id:event.event_id};}
 async report(from:string,to:string){if(Number.isNaN(Date.parse(from))||Number.isNaN(Date.parse(to)))throw new ReportingError('from/to must be ISO date-times.');const rows=await this.pool.query<{event_type:string;count:string}>('SELECT event_type,count(*)::text count FROM rpa_run_events WHERE occurred_at >= $1 AND occurred_at < $2 GROUP BY event_type',[from,to]);const metrics=Object.fromEntries(rows.rows.map(r=>[r.event_type,Number(r.count)]));const terminal=(metrics.completed??0)+(metrics.failed??0)+(metrics.cancelled??0)+(metrics.skipped??0);return{schema_version:1,from,to,timezone:'Asia/Bangkok',counts:metrics,success_rate:terminal?Number((((metrics.completed??0)/terminal)*100).toFixed(2)):0};}
 async enqueue(id:string,target:string,message:string){await this.pool.query('INSERT INTO notification_outbox(id,target_id,message) VALUES($1,$2,$3) ON CONFLICT(id) DO NOTHING',[id,target,safe(message)]);}
}
function validate(e:RpaEvent){if(!e||e.schema_version!==1||!e.event_id?.trim()||!e.run_id?.trim()||!e.bot_id?.trim()||!e.project_id?.trim()||!['dev','uat','prod','local','unknown'].includes(e.environment)||!['started','completed','failed','cancelled','skipped'].includes(e.event_type)||Number.isNaN(Date.parse(e.occurred_at)))throw new ReportingError('RPA run event contract is invalid.');}
function validateWorkflow(e:WorkflowEvent){if(!e||e.schema_version!==1||!e.event_id?.trim()||!['ai_sdlc_job','project_plan','deployment'].includes(e.aggregate_type)||!e.aggregate_id?.trim()||!e.event_type?.trim()||Number.isNaN(Date.parse(e.occurred_at))||!e.payload||typeof e.payload!=='object'||Array.isArray(e.payload))throw new ReportingError('Workflow event contract is invalid.');}
function sanitize<T>(value:T):T{return JSON.parse(JSON.stringify(value,(key,item)=>/(password|token|cookie|secret|stack|screenshot)/i.test(key)?undefined:typeof item==='string'?safe(item):item));}
export function safe(value:string){return value.replace(/(bearer\s+|token[=:]\s*|password[=:]\s*)[^\s]+/gi,'$1<redacted>').slice(0,4000);}
function hash(v:string){return createHash('sha256').update(v).digest('hex').slice(0,24);}
function label(value:WorkflowEvent['aggregate_type']){return value==='ai_sdlc_job'?'AI SDLC job':value==='project_plan'?'Phase 5 plan':'Deployment';}
