import { readFile } from 'node:fs/promises'; import { dirname, resolve } from 'node:path'; import { fileURLToPath } from 'node:url'; import pg from 'pg';
import { HttpActionExecutor } from './executor.js'; import { createControlServer } from './http.js'; import { parseIdentities } from './security.js'; import { WorkflowControlService } from './service.js'; import { PostgresActionStore } from './store.js';
import { ReportingActionEventPublisher } from './reporting-events.js';
const pool = new pg.Pool({ connectionString: required('DATABASE_URL') }); await pool.query(await readFile(resolve(dirname(fileURLToPath(import.meta.url)), '../sql/001_workflow_control.sql'), 'utf8'));
const jiraAuthorization = `Basic ${Buffer.from(`${required('JIRA_EMAIL')}:${required('JIRA_API_TOKEN')}`).toString('base64')}`;
const phase4Url = required('PHASE4_API_URL'); const phase4Token = required('PHASE4_API_TOKEN');
const executor = new HttpActionExecutor({ jiraBaseUrl: required('JIRA_BASE_URL'), jiraAuthorization, jiraAiAssigneeAccountId: required('JIRA_AI_PRIMARY_ASSIGNEE_ACCOUNT_ID'), jiraWorkTypeFieldId: process.env.JIRA_WORK_TYPE_FIELD_ID, phase4Url, phase4Token, phase5Url: required('PHASE5_API_URL'), phase5Token: required('PHASE5_API_TOKEN'), actorSigningSecret: required('ACTOR_SIGNING_SECRET'),governanceRoot:process.env.GOVERNANCE_ROOT??'/governance', githubApiUrl: process.env.GITHUB_API_URL, githubAuthorization: `Bearer ${required('GITHUB_TOKEN')}` });
const server = createControlServer({ apiToken: required('WORKFLOW_CONTROL_API_TOKEN'), gatewayToken: required('WORKFLOW_CONTROL_GATEWAY_TOKEN'), principalSecret: required('PRINCIPAL_SIGNING_SECRET'), identities: parseIdentities(required('LINE_IDENTITIES_JSON')), phase4Url, phase4Token, phase5Url:required('PHASE5_API_URL'),phase5Token:required('PHASE5_API_TOKEN'),contextUrl:required('CONTEXT_RESOLVER_URL'),contextToken:required('CONTEXT_RESOLVER_API_TOKEN'),jiraWebhookSecret:required('JIRA_WEBHOOK_SECRET'),jiraWorkTypeFieldId:required('JIRA_WORK_TYPE_FIELD_ID'),jiraAiAssignees:csv(required('JIRA_AI_ASSIGNEE_ACCOUNT_IDS')),jiraAllowedProjects:csv(required('JIRA_ALLOWED_PROJECT_KEYS')),jiraModuleNameFieldId:process.env.JIRA_MODULE_NAME_FIELD_ID,jiraTargetPathFieldId:process.env.JIRA_TARGET_PATH_FIELD_ID,jiraProjectIdFieldId:process.env.JIRA_PROJECT_ID_FIELD_ID,jiraDomainFieldId:process.env.JIRA_DOMAIN_FIELD_ID,jiraProjectTypeFieldId:process.env.JIRA_PROJECT_TYPE_FIELD_ID,jiraDeploymentTypeFieldId:process.env.JIRA_DEPLOYMENT_TYPE_FIELD_ID,jiraRepositoryFieldId:process.env.JIRA_REPOSITORY_FIELD_ID }, new WorkflowControlService(new PostgresActionStore(pool), executor, Number(process.env.ACTION_TTL_SECONDS ?? '600'), new ReportingActionEventPublisher(required('REPORTING_API_URL'), required('REPORTING_API_TOKEN'))));
const port = Number(process.env.WORKFLOW_CONTROL_PORT ?? '8087'); server.listen(port, '0.0.0.0', () => console.log(JSON.stringify({ service: 'workflow-control', port }))); process.on('SIGTERM', () => server.close(() => void pool.end()));
function required(name: string): string { const value = process.env[name]; if (!value) throw new Error(`${name} is required.`); return value; }
function csv(value:string){return value.split(',').map(v=>v.trim()).filter(Boolean);}
